spring:
  application:
    name: request-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:requestdb}
    username: ${DB_USER:request}
    password: ${DB_PASSWORD:request}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #jpa.hibernate.ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC

  flyway:
    enabled: false #true, if write migration

server:
  port: 8081
