spring:
  application:
    name: request-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:requestdb}
    username: ${DB_USER:request}
    password: ${DB_PASSWORD:request}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate #jpa.hibernate.ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC

  flyway:
    enabled: true #true, if write migration

server:
  port: 8081

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha

ai:
  localai:
    base-url: ${LOCALAI_BASE_URL:http://localhost:8080}